# This file was automatically @generated by Smaug.
# Do not manually edit this file. Edit Smaug.toml instead.

require "smaug/zif/lib/require.rb"
require "smaug/dr-input-manager/lib/input_manager.rb"

